### ISSUE TITLE
Travis CI  idempotence test alwais fails on ansible 2.2.0.0

### ISSUE THREAD

**Issue by gites** [kbrebanov/ansible-powerdns#3]
Travis CI  idempotentce test always fails on ansible 2.2.0.0 due to `update_cache: yes` when installing packages (https://github.com/kbrebanov/ansible-powerdns/blob/master/tasks/Ubuntu.yml#L37 and https://github.com/kbrebanov/ansible-powerdns/blob/master/tasks/Ubuntu.yml#L50).

On 2.1.x this was fine, but 2.2.x reports this tasks as changed:
```
TASK [ansible-powerdns : Install PowerDNS authoritative] ***********************
changed: [localhost] => (item=[u'pdns-server=4.0.1*']) => {"cache_update_time": 1478676388, "cache_updated": true, "changed": true, "item": ["pdns-server=4.0.1*"]}

TASK [ansible-powerdns : Install PowerDNS recursor] ****************************
changed: [localhost] => (item=[u'pdns-recursor=4.0.3*']) => {"cache_update_time": 1478676393, "cache_updated": true, "changed": true, "item": ["pdns-recursor=4.0.3*"]}

```

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
